server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: prod

  cloud:
    config:
      server:
        git:
          uri: git@github.com:RIN-1011/explorer-config.git
          default-label: main
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACDMInmPB/nSz2eVi2/XC7kKSKSOp2AzwsMSHudlJtXcXAAAAJglbSeSJW0n
            kgAAAAtzc2gtZWQyNTUxOQAAACDMInmPB/nSz2eVi2/XC7kKSKSOp2AzwsMSHudlJtXcXA
            AAAEBC4mrOLjJl3hHqmwiEBf8/o7JA+PsT0k4QLTskpUudF8wieY8H+dLPZ5WLb9cLuQpI
            pI6nYDPCwxIe52Um1dxcAAAAFVNTQUZZQERFU0tUT1AtTEw4MzJGNA==
            -----END OPENSSH PRIVATE KEY-----


passphrase:
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

---

spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ip-address: 3.36.60.98
    hostname: config-service
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.36.60.98:8761/eureka

---

spring:
  config:
    activate:
      on-profile: dev

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ip-address: localhost
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka